export default {
    products: [
        {
            _id: 123,
            name: 'slim shart',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id: 124,
            name: 'Bast pant',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 125,
            name: 'short',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 8,
        },
        {
            _id: 126,
            name: 'slim shart',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: 127,
            name: 'slim shart',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 9,
        },
        {
            _id: 128,
            name: 'slim shart',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nick',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }
    ]
}