export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PORDUCT_LIST_FAIL = 'PORDUCT_LIST_FAIL';

export const PORDUCT_DETAILS_REQUEST = 'PORDUCT_DETAILS_REQUEST';
export const PORDUCT_DETAILS_SUCCESS = 'PORDUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';